[package]
name = "LcsAggregator"
version = "0.0.0"

[dependencies]
#Econia = { git = "https://github.com/manahip/econia.git", subdir = "src/move/econia", rev = "5721a6586dec90c292b1655497247c3c1ebf51e5" }
CoinList = { git = "https://github.com/hippospace/aptos-coin-list.git", subdir = "", rev = "cc2100fb533f8b989a2c28c64a15c52007a91945" }
Liquidswap = { local = "./interface/pontem-Liquidswap" }
#basiq = { local = "./interface/basiq-basiq" }
ditto-staking = { local = "./interface/ditto-research" }
Tortuga = { local = "./interface/tortuga" }
TortugaGovernance = { local = "./interface/tortuga-stake-coin" }
Aptoswap = { local = "./interface/aptoswap" }
aux = { local = "./interface/aux"}
AnimeSwapV1 = { local = "./interface/animeswap" }
Cetue-AMM = { local = "./interface/cetus-amm" }
PancakeSwap = { local = "./interface/pancake" }
obric-swap = { local = "./interface/obric" }

[addresses]
lcs_aggregator = "0xc8f5f290fe0d155933cfc2cdd13ae11ba97abb4f413770091c3ab70cacc6adae"
poster = "0x12"
poster_2 = "0x13"
