[package]
name = "Liquidswap"
version = "0.4.1"
upgrade_policy = "immutable"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "ba5fa41f82bfe3d4e314d41c39fca77131e9f208"
subdir = "aptos-move/framework/aptos-framework"
[dependencies.UQ64x64]
git = "https://github.com/pontem-network/UQ64x64.git"
rev = "v0.3.7"
[dependencies.U256]
git = "https://github.com/pontem-network/U256.git"
rev = "v0.3.8"
[dependencies.LiquidswapLP]
local = "../pontem-LiquidswapLP/"

[addresses]
liquidswap = "0x190d44266241744264b964a37b8f09863167a12d3e70cda39376cfb4e3561e12"
# Resource accounts: should be the same as @liquidswap_lp in lp_coin
liquidswap_pool_account = "0x05a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948"
liquidswap_emergency_account = "0xa6d6e549b917e454464ff6c63f91386d98769ea512bc778bdaca00969f896764"


